#ifndef CORRUPTEDFILEFILTER_GLOBAL_H
#define CORRUPTEDFILEFILTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CORRUPTEDFILEFILTER_LIBRARY)
#  define CORRUPTEDFILEFILTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CORRUPTEDFILEFILTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CORRUPTEDFILEFILTER_GLOBAL_H
