#ifndef MD5HASHFILTER_GLOBAL_H
#define MD5HASHFILTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MD5HASHFILTER_LIBRARY)
#  define MD5HASHFILTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MD5HASHFILTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MD5HASHFILTER_GLOBAL_H
