#ifndef IDENTICALIMAGEFILTER_GLOBAL_H
#define IDENTICALIMAGEFILTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(IDENTICALIMAGEFILTER_LIBRARY)
#  define IDENTICALIMAGEFILTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define IDENTICALIMAGEFILTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // IDENTICALIMAGEFILTER_GLOBAL_H
