#ifndef CASEMISMATCHFILTER_GLOBAL_H
#define CASEMISMATCHFILTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CASEMISMATCHFILTER_LIBRARY)
#  define CASEMISMATCHFILTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CASEMISMATCHFILTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CASEMISMATCHFILTER_GLOBAL_H
